spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/beans
    username: beans
    password: beans
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
      show-sql: true
    flyway:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
beans:
  checkout:
    hold-duration: PT15M
    min-shelf-life-days: 30
